export interface Federation {
    code: string;
    name: string;
}

export const FEDERATIONS: Federation[] = [
    { code: "ACC", name: "ASEAN Chess Confederation" },
    { code: "ACF", name: "Asian Chess Federation" },
    { code: "AFG", name: "Afghanistan" },
    { code: "AHO", name: "Netherlands Antilles" },
    { code: "ALB", name: "Albania" },
    { code: "ALG", name: "Algeria" },
    { code: "AND", name: "Andorra" },
    { code: "ANG", name: "Angola" },
    { code: "ANT", name: "Antigua and Barbuda" },
    { code: "ARG", name: "Argentina" },
    { code: "ARM", name: "Armenia" },
    { code: "ARU", name: "Aruba" },
    { code: "AUS", name: "Australia" },
    { code: "AUT", name: "Austria" },
    { code: "AZE", name: "Azerbaijan" },
    { code: "BAH", name: "Bahamas" },
    { code: "BAN", name: "Bangladesh" },
    { code: "BAR", name: "Barbados" },
    { code: "BDI", name: "Burundi" },
    { code: "BEL", name: "Belgium" },
    { code: "BEN", name: "Benin Republic" },
    { code: "BHU", name: "Bhutan" },
    { code: "BIH", name: "Bosnia & Herzegovina" },
    { code: "BLR", name: "Belarus" },
    { code: "BOL", name: "Bolivia" },
    { code: "BOT", name: "Botswana" },
    { code: "BRA", name: "Brazil" },
    { code: "BRN", name: "Bahrain" },
    { code: "BRU", name: "Brunei" },
    { code: "BUL", name: "Bulgaria" },
    { code: "BUR", name: "Burkina Faso" },
    { code: "CAF", name: "Central African Republic" },
    { code: "CAM", name: "Cambodia" },
    { code: "CAN", name: "Canada" },
    { code: "CAT", name: "Catalonia" },
    { code: "CAY", name: "Cayman Islands" },
    { code: "CCA", name: "Confederation of Chess for Americas" },
    { code: "CHI", name: "Chile" },
    { code: "CHN", name: "China" },
    { code: "CIV", name: "Ivory Coast" },
    { code: "CMR", name: "Cameroon" },
    { code: "COL", name: "Colombia" },
    { code: "CPV", name: "Cape Verde" },
    { code: "CRC", name: "Costa Rica" },
    { code: "CRO", name: "Croatia" },
    { code: "CUB", name: "Cuba" },
    { code: "CYP", name: "Cyprus" },
    { code: "CZE", name: "Czech Republic" },
    { code: "DEN", name: "Denmark" },
    { code: "DJI", name: "Djibouti" },
    { code: "DOM", name: "Dominican Republic" },
    { code: "ECX", name: "European Chess Union" },
    { code: "ECU", name: "Ecuador" },
    { code: "EGY", name: "Egypt" },
    { code: "ENG", name: "England" },
    { code: "ESA", name: "El Salvador" },
    { code: "ESP", name: "Spain" },
    { code: "EST", name: "Estonia" },
    { code: "ETH", name: "Ethiopia" },
    { code: "FAI", name: "Faroe Islands" },
    { code: "FID", name: "FIDE" },
    { code: "FIJ", name: "Fiji" },
    { code: "FIN", name: "Finland" },
    { code: "FRA", name: "France" },
    { code: "GAB", name: "Gabon" },
    { code: "GAM", name: "Gambia" },
    { code: "GCI", name: "Guernsey" },
    { code: "GEO", name: "Georgia" },
    { code: "GEQ", name: "Equatorial Guinea" },
    { code: "GER", name: "Germany" },
    { code: "GHA", name: "Ghana" },
    { code: "GIN", name: "Guinea" },
    { code: "GRE", name: "Greece" },
    { code: "GUA", name: "Guatemala" },
    { code: "GUM", name: "Guam" },
    { code: "GUY", name: "Guyana" },
    { code: "HAI", name: "Haiti" },
    { code: "HKG", name: "Hong Kong" },
    { code: "HON", name: "Honduras" },
    { code: "HUN", name: "Hungary" },
    { code: "INA", name: "Indonesia" },
    { code: "IND", name: "India" },
    { code: "IOM", name: "Isle of Man" },
    { code: "IRI", name: "Iran" },
    { code: "IRL", name: "Ireland" },
    { code: "IRQ", name: "Iraq" },
    { code: "ISL", name: "Iceland" },
    { code: "ISR", name: "Israel" },
    { code: "ISV", name: "US Virgin Islands" },
    { code: "ITA", name: "Italy" },
    { code: "IVB", name: "British Virgin Islands" },
    { code: "JAM", name: "Jamaica" },
    { code: "JCI", name: "Jersey" },
    { code: "JOR", name: "Jordan" },
    { code: "JPN", name: "Japan" },
    { code: "KAZ", name: "Kazakhstan" },
    { code: "KEN", name: "Kenya" },
    { code: "KGZ", name: "Kyrgyzstan" },
    { code: "KOR", name: "South Korea" },
    { code: "KOS", name: "Kosovo" },
    { code: "KSA", name: "Saudi Arabia" },
    { code: "KUW", name: "Kuwait" },
    { code: "LAO", name: "Laos" },
    { code: "LAT", name: "Latvia" },
    { code: "LBA", name: "Libya" },
    { code: "LBN", name: "Lebanon" },
    { code: "LBR", name: "Liberia" },
    { code: "LCA", name: "Saint Lucia" },
    { code: "LES", name: "Lesotho" },
    { code: "LIE", name: "Liechtenstein" },
    { code: "LTU", name: "Lithuania" },
    { code: "LUX", name: "Luxembourg" },
    { code: "MAC", name: "Macau" },
    { code: "MAD", name: "Madagascar" },
    { code: "MAR", name: "Morocco" },
    { code: "MAS", name: "Malaysia" },
    { code: "MAW", name: "Malawi" },
    { code: "MDA", name: "Moldova" },
    { code: "MDV", name: "Maldives" },
    { code: "MEX", name: "Mexico" },
    { code: "MGL", name: "Mongolia" },
    { code: "MKD", name: "North Macedonia" },
    { code: "MLI", name: "Mali" },
    { code: "MLT", name: "Malta" },
    { code: "MNC", name: "Monaco" },
    { code: "MNE", name: "Montenegro" },
    { code: "MOZ", name: "Mozambique" },
    { code: "MRI", name: "Mauritius" },
    { code: "MTN", name: "Mauritania" },
    { code: "MYA", name: "Myanmar" },
    { code: "NAM", name: "Namibia" },
    { code: "NCA", name: "Nicaragua" },
    { code: "NED", name: "Netherlands" },
    { code: "NEP", name: "Nepal" },
    { code: "NGR", name: "Nigeria" },
    { code: "NIG", name: "Niger" },
    { code: "NIR", name: "Northern Ireland" },
    { code: "NOR", name: "Norway" },
    { code: "NRU", name: "Nauru" },
    { code: "NZL", name: "New Zealand" },
    { code: "OMA", name: "Oman" },
    { code: "ONL", name: "Online Tournaments" },
    { code: "PAK", name: "Pakistan" },
    { code: "PAN", name: "Panama" },
    { code: "PAR", name: "Paraguay" },
    { code: "PER", name: "Peru" },
    { code: "PHI", name: "Philippines" },
    { code: "PLE", name: "Palestine" },
    { code: "PLW", name: "Palau" },
    { code: "PNG", name: "Papua New Guinea" },
    { code: "POL", name: "Poland" },
    { code: "POR", name: "Portugal" },
    { code: "PUR", name: "Puerto Rico" },
    { code: "QAT", name: "Qatar" },
    { code: "ROU", name: "Romania" },
    { code: "RSA", name: "South Africa" },
    { code: "RUS", name: "Russia" },
    { code: "RWA", name: "Rwanda" },
    { code: "SCG", name: "Yugoslavia" },
    { code: "SCO", name: "Scotland" },
    { code: "SEN", name: "Senegal" },
    { code: "SEY", name: "Seychelles" },
    { code: "SGP", name: "Singapore" },
    { code: "SLE", name: "Sierra Leone" },
    { code: "SLO", name: "Slovenia" },
    { code: "SMR", name: "San Marino" },
    { code: "SOL", name: "Solomon Islands" },
    { code: "SOM", name: "Somalia" },
    { code: "SRB", name: "Serbia" },
    { code: "SRI", name: "Sri Lanka" },
    { code: "SSD", name: "South Sudan" },
    { code: "STP", name: "Sao Tome and Principe" },
    { code: "SUD", name: "Sudan" },
    { code: "SUI", name: "Switzerland" },
    { code: "SUR", name: "Suriname" },
    { code: "SVK", name: "Slovakia" },
    { code: "SWE", name: "Sweden" },
    { code: "SWZ", name: "Swaziland" },
    { code: "SYR", name: "Syria" },
    { code: "TAN", name: "Tanzania" },
    { code: "THA", name: "Thailand" },
    { code: "TJK", name: "Tajikistan" },
    { code: "TKM", name: "Turkmenistan" },
    { code: "TLS", name: "Timor-Leste" },
    { code: "TOG", name: "Togo" },
    { code: "TON", name: "Tonga" },
    { code: "TPE", name: "Chinese Taipei" },
    { code: "TTO", name: "Trinidad and Tobago" },
    { code: "TUN", name: "Tunisia" },
    { code: "TUR", name: "Republic of Türkiye" },
    { code: "UAE", name: "United Arab Emirates" },
    { code: "UGA", name: "Uganda" },
    { code: "UKR", name: "Ukraine" },
    { code: "URU", name: "Uruguay" },
    { code: "USA", name: "United States of America" },
    { code: "UZB", name: "Uzbekistan" },
    { code: "VAN", name: "Vanuatu" },
    { code: "VEN", name: "Venezuela" },
    { code: "VIE", name: "Vietnam" },
    { code: "WFC", name: "World Federation for Chess Composition" },
    { code: "WLS", name: "Wales" },
    { code: "XXX", name: "For testing purposes" },
    { code: "YEM", name: "Yemen" },
    { code: "ZAM", name: "Zambia" },
    { code: "ZIM", name: "Zimbabwe" },
    { code: "ZZZ", name: "All other countries" },
];
